name: BanSystem
version: 1.0.0
main: us.th3controller.bansystem.BanSystem
author: th3controller
commands:
  ban:
    description: Bans the specified player
    usage: /<command> (player) [reason]
    aliases: bannish
  kick:
    description: Kicks the specified player
    usage: /<command> (player) [reason]
  tempban:
    description: Temporarily bans the specified player
    usage: /<command> (player) [reason]
